version: "3.1"
services:
  devbook-db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - devbook-db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mynet

networks:
  mynet:
    driver: "bridge"
volumes:
  devbook-db-data:
  init: