CREATE DATABASE IF NOT EXISTS devbook;

GRANT ALL PRIVILEGES ON devbook.* TO 'lazarok09'@'%';

USE devbook;

CREATE TABLE Book (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);